### ISSUE TITLE
vanillaJS version

### ISSUE THREAD

**Issue by naugtur** [filamentgroup/tappy#13]
I'm not one of those jQuery haters, but tappy is so small that it could be handy for projects that don't have jQuery as a dependency. 

I'd gladly contribute a vanillaJS version, especially that I know the size of the testing infrastructure you have access to. BTW, are you going to write a test suite for tappy?

**Comment by pukhalski** [comment]
@naugtur, @toddparker, a package I created a while ago: https://github.com/pukhalski/tap

jQuery-less and pointerEvents support.

**Comment by zachleat** [comment]
Per [our unmaintained repository status documentation](https://github.com/filamentgroup/standards-and-conventions/blob/master/repository-maintenance.md#unmaintained) this repository is now retired and all open issues and pull requests will now be closed.

The touch delay in web browsers has [been solved natively](https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away)! Hooray 🎉!
