### ISSUE TITLE
Tappy repeating action

### ISSUE THREAD

**Issue by marceloudi** [filamentgroup/tappy#15]
Hi! You did a great job!
Testing it on an older (and slow) android 4.1.1 tablet, it really solve the delay problem.

But, the code, sometimes, "repeat" the click action, as you can see in the following video (not listed):

https://www.youtube.com/watch?v=RSYpgNaCsZc

The problem occurs at 0:13 seconds on video.

Well, changing tappy code, after increasing the timeout to 100000, the issue seems to be reduced (almost solved):

```
resetTimer = setTimeout( function(){
      w.tapHandling = false;
      cancel = false;
}, 100000 );
```

I did not test it on faster devices.

This is an expected behavior?

Can I do something to help you in this issue?

Regards!

Marcelo Amorim

**Comment by zachleat** [comment]
Per [our unmaintained repository status documentation](https://github.com/filamentgroup/standards-and-conventions/blob/master/repository-maintenance.md#unmaintained) this repository is now retired and all open issues and pull requests will now be closed.

The touch delay in web browsers has [been solved natively](https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away)! Hooray 🎉!
