### ISSUE TITLE
Documentation should suggest .on instead of .bind

### ISSUE THREAD

**Issue by mikehdt** [filamentgroup/tappy#24]
The documentation suggests using .bind() to attach Tappy to elements; however, from the jQuery docs as of jQuery 1.7, .on() is now the preferred way to do this. .bind() still works, but it is run through .on(), and so incurs a miniscule performance penalty.

http://api.jquery.com/bind/ - docs
http://stackoverflow.com/questions/11847021/jquery-bind-vs-on - a question about which one, as I wondered about .bind() when I read it here and this was the first thing I read.

Thanks :)

**Comment by jefflembeck** [comment]
Since tappy monkey-patches `.bind`, it's probably best we leave it as is, but I'd be up to hear other voices on the topic.

**Comment by scottjehl** [comment]
It’ll use the special events api if available, so `on` should work just as well when using jQuery.

In libs that don’t have a special events api though, it will monkey patch bind. 

Related issue: https://github.com/filamentgroup/tappy/issues/22

**Comment by mikehdt** [comment]
I've now run into a new situation where this has become a limitation. If you are dynamically injecting elements (via Ajax or similar), then you cannot bind Tappy to them, as this fails silently:
$(someParentSelector).on('tap', '.element-to-dynamically-bind', functionToCall);

This is unfortunate, as it means that things like ajax pagination, where you have items on pages which would benefit from Tappy's removal of the double-click pause, cannot be bound to.

**Comment by thdoan** [comment]
@mikehdt Does it still fail if someParentSelector = 'body'? If yes, then I guess you'll have to revert to rebinding 'tap' to the newly injected elements.

**Comment by zachleat** [comment]
Per [our unmaintained repository status documentation](https://github.com/filamentgroup/standards-and-conventions/blob/master/repository-maintenance.md#unmaintained) this repository is now retired and all open issues and pull requests will now be closed.

The touch delay in web browsers has [been solved natively](https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away)! Hooray 🎉!
