### ISSUE TITLE
Hello, about jquery clone(true)

### ISSUE THREAD

**Issue by awesomejerry** [filamentgroup/tappy#25]
First, it works great on iOS device! (Thank you so much) However, when I'm using deep clone, it seems to fire twice.

Here's the circumstance:
    $('#a').on('tap', function(){
        console.error('a');
    });
    $('#a').clone(true).appendTo($('body'));

it works with the first element, but the cloned element fires twice though.

Is there a workaround to deal with clone??

**Comment by awesomejerry** [comment]
Just tested it out. If I turn
if( $.event && $.event.special ) ---> if(false)

it works.

**Comment by awesomejerry** [comment]
I assume it's something wrong with special events api

**Comment by geertbrit** [comment]
This is probably related to the caveats mentioned in the docs (see the bottom of the page): 

Quoted:
- Do not bind a child node to the tap event when a parent node is already bound.
- Do not bind a tap event more than once to a single element.

**Comment by awesomejerry** [comment]
Don't know if it's related to those circumstance. I'm not binding the event to the parent and not bind it twice. I'm not quite familiar with special events api's add function very clearly. Maybe it's the mechanism that won't allow this happening. Anyway, thanks for pointing me out that there are things I haven't noticed before.
