### ISSUE TITLE
VoiceOver

### ISSUE THREAD

**Issue by leifdejong** [filamentgroup/tappy#26]
VoiceOver 'click' does not trigger 'tap'.

In Voice Over (VO) on iOS devices, 'Tap' is never fired. 

Replication: 
1. Bind an element to 'tap'
2. Turn on Voice Over
3. Double tap to 'click'

Expected: 
1. Event handler should fire

VO does a click and somewhere, that event gets lost. The workaround was to bind both events (click, tap) and then throw 'click' away if 'tap' is recognized. If tap is not found, it goes ahead and fires the click event. 

Solution: 

My recommendation would be to bind the `click` when the 'tap' is bound and do some checks internally. This is the only way as we can know when voiceover is being used. Will be working on a fix.

**Comment by zachleat** [comment]
Per [our unmaintained repository status documentation](https://github.com/filamentgroup/standards-and-conventions/blob/master/repository-maintenance.md#unmaintained) this repository is now retired and all open issues and pull requests will now be closed.

The touch delay in web browsers has [been solved natively](https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away)! Hooray 🎉!
