### ISSUE TITLE
the scroll detection should look for Left-right scroll too, for wider-than viewport pages 

### ISSUE THREAD

**Issue by scottjehl** [filamentgroup/tappy#5]

**Comment by zachleat** [comment]
Per [our unmaintained repository status documentation](https://github.com/filamentgroup/standards-and-conventions/blob/master/repository-maintenance.md#unmaintained) this repository is now retired and all open issues and pull requests will now be closed.

The touch delay in web browsers has [been solved natively](https://developers.google.com/web/updates/2013/12/300ms-tap-delay-gone-away)! Hooray 🎉!
